### ISSUE TITLE
در بخش لاگ اندروید این ارور میاد

### ISSUE THREAD

**Issue by sepehr13494** [chabokpush/chabok-panel#25]
E/com.adpdigital.push.AdpPushClient: Cannot save device, Reason: Unauthorized
    org.apache.http.client.HttpResponseException: Unauthorized
        at a.f.sendResponseMessage(SourceFile:440)
        at a.e.run(SourceFile:2078)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)

**Comment by behrad** [comment]
با سلام
این خطا مربوط به بخش اندروید میشه نه پنل
لطفن در بخش درست سوالتون رو مطرح کنید:
https://github.com/chabokpush/chabok-client-android/issues

ضمنن از پیام خطای شما مشخص هست که توکن‌هاتون رو درست در کدتون کپی نکرده اید
توکن‌های شما در پنل بخش تنظیمات موجود هست و مستندات مربوط به نحوه استفاده ازشون نیز در بخش مستندات هست
